Entry.create!(name: "Nick")
Entry.create!(name: "Kristoph")
Entry.create!(name: "Shovan")
Entry.create!(name: "Todd")
Entry.create!(name: "Joshua")
Entry.create!(name: "Mike")
Entry.create!(name: "Jea")
